[project]
name = "locus"
version = "0.1.0"
description = "Extract and cache snips from bioinformatics data files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "diskcache>=5.6.3",
    "hictkpy>=1.3.0",
]
